# -*- coding: utf-8 -*-
"""Lab_01_Pandas_Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJEfMs5tpusMbHvVq_Z8Ys1JODACBye1
"""

# import modules
import pandas as pd
import matplotlib.pyplot as plt

main_data = pd.read_csv('Data_for_Transformation.csv')
plt.scatter(main_data["Age"], main_data["Salary"])
plt.xlabel("Age")
plt.ylabel("Salary")
plt.show()

plt.hist(main_data["Salary"], bins = 10, color = "yellow")
plt.xlabel("Salaries")
plt.show()

fig_size = plt.figure(figsize=(7, 5))
plt.bar(main_data["Country"], main_data["Salary"], color="green")
plt.xlabel("Salaries")
plt.ylabel("Countries")
plt.title("Bar chart of country vs salary")
plt.show()