# -*- coding: utf-8 -*-
"""Lab_01_Linear_Algebra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_CZDW_cof69tl0jJEpq9tk3i0ZQV6oV
"""

import numpy as np
import pandas as pd

# two matrics
array1 = np.array([[5, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[7, -8]])
print(array1)
print(array2)

#randomly initialize array
array = np.random.rand(2, 4)
print(array)

# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

# mean of first matrix
mean = np.mean(array1)
print(mean)

main_data = pd.read_csv("mtcars.csv")

del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())